# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [7]:
!python -V

Python 3.7.11


# 1.3 Trabalhando com arrays Numpy

In [9]:
import numpy as np


In [ ]:
km = np.loadtxt('carros-km.txt')
print(km)

In [ ]:
anos = np.loadtxt('carros-anos.txt', dtype = int)
anos

### Obtendo a quilometragem média por ano

In [ ]:
km_media = km / (2021 - anos)
km_media

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [20]:
2+2

4

### Subtração ($-$)

In [19]:
2-2

0

### Multiplicação ($*$)

In [18]:
2*2

4

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [17]:
30/7

4.285714285714286

In [21]:
30 // 7

4

### Exponenciação ($**$)

In [22]:
2 ** 3

8

### Resto da divisão ($\%$)

In [23]:
30%7

2

In [24]:
30%6

0

### Expressões matemáticas

In [25]:
5*2 + 3*7

31

In [26]:
(5*2) + (3*7)

31

In [28]:
5*(2 + 3)*7

175

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [29]:
_

175

In [30]:
5*2


10

In [31]:
_ + 10

20

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variável $\ne$ nome_da_variavel $\ne$ NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [33]:
ano_atual =2021 
ano_fabricacao = 2003
km_total = 55930.45

In [35]:
ano_atual 

2021

In [36]:
ano_fabricacao

2003

In [37]:
km_total

55930.45

# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [39]:
km_media = km_total / (ano_atual - ano_fabricacao)

In [41]:
ano_atual =2021 
ano_fabricacao = 2003
km_total = 55930.45
km_media = km_total / (ano_atual - ano_fabricacao)  

#no proximo ano

km_total = km_total + km_media
km_total

59037.69722222222

In [43]:
ano_atual =2021 
ano_fabricacao = 2003
km_total = 55930.45
km_media = km_total / (ano_atual - ano_fabricacao)  

km_total += km_media
km_total

59037.69722222222

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [45]:
ano_atual, ano_fabricacao, km_total = 2021, 2003, 55930.45


In [46]:
ano_atual

2021

In [47]:
ano_fabricacao

2003

In [48]:
km_total

55930.45

# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [52]:
type(ano_atual)

int

In [53]:
type(km_total)

float

### Booleanos

In [54]:
zero_km = True  

In [55]:
type(zero_km)

bool

In [57]:
zero_km = False  

In [56]:
type(zero_km)

bool

### Strings

In [58]:
nome = 'Jeep Renegade'
nome

'Jeep Renegade'

In [59]:
nome = 'Jeep "Renegade"'
nome

'Jeep "Renegade"'

In [61]:
carro = ''' 
  Modelo
  Ano
  Fabricante 
'''

In [62]:
type(carro)

str

### None

In [64]:
quilometragem = None
quilometragem

In [65]:
type(quilometragem)

NoneType

# 2.4 Conversão de tipos

In [74]:
a = 10
b = 20
c = "Python é "
d = "útil"

In [68]:
type(a) 

int

In [69]:
type(b)

int

In [70]:
type(c)

str

In [71]:
type(d)

str

In [72]:
a + b

30

In [75]:
c + d

'Python é útil'

In [76]:
# c + a

TypeError: ignored

### Conversões de tipo

Funções int(), float(), str()

In [77]:
str(a)

'10'

In [78]:
type(str(a))

str

In [79]:
c + str(a)

'Python é 10'

In [80]:
float(a)

10.0

In [84]:
pi = 3.141592

In [85]:
int(pi)

3

In [86]:
var = 3.99

In [87]:
int(var)
# como pode ser observado ele não faz o arredondamento, apenas pega a parte inteira

3

# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [91]:
ano_atual = 2021
ano_fabricacao = 2021

if (ano_atual == ano_fabricacao):
    print('Verdadeiro')
else:
    print('Falso')

Verdadeiro


### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [ ]:
# Uma dica que pode ser útil nos estudos é
# se vc pressiona 'ctr + ;' vc comenta e descomenta tudo que estiver selecionado
# ou apenas a linha que o cursor estiver

In [92]:
# Isto é um comentário
ano_atual = 2021
ano_atual

2021

In [93]:
# Isto
# é um 
# comentário
ano_atual = 2021
ano_atual

2021

In [94]:
'''Isto é um
comentário'''
ano_atual = 2021
ano_atual

2021

In [96]:
# Definindo variáveis
ano_atual = 2021
ano_fabricacao = 2025

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
    print('Verdadeiro')
else:                               # Testando se condição é falsa
    print('Falso')

Falso


### Formatação de *strings*

## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [100]:
print("Olá, {}!".format('estou apredendo a usar a formatação de string'))

Olá, estou apredendo a usar a formatação de string!


In [102]:
print("Olá, {}! É incrível como pode ser tão divertido aprender {}".format('estou apredendo a usar a formatação de string', 'Pyhton'))

Olá, estou apredendo a usar a formatação de string! É incrível como pode ser tão divertido aprender Pyhton


In [103]:
print("Olá, {fomatacao}! É incrível como pode ser tão divertido aprender {linguagem}".format(formatacao = 'estou apredendo a usar a formatação de string', linguagem = 'Pyhton'))

Olá, estou apredendo a usar a formatação de string! É incrível como pode ser tão divertido aprender Pyhton


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [104]:
formatacao = 'estou apredendo a usar a formatação de string'
linguagem = 'Pyhton'

In [107]:
print(f"Olá, {formatacao}! É incrível como pode ser tão divertido aprender {linguagem}")

Olá, estou apredendo a usar a formatação de string! É incrível como pode ser tão divertido aprender Pyhton


# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [108]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

### Lista com tipos de dados variados

In [109]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [110]:
Carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [111]:
Carro_2

['Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
 106161.94]

In [151]:
Carros = [Carro_1,Carro_2]
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [113]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [114]:
'Piloto automático' in Acessorios

True

In [115]:
'Teto Solar' in Acessorios

False

In [116]:
'Piloto automático' not in Acessorios

False

In [117]:
'Teto Solar' not in Acessorios

True

## *A + B*

Concatena as listas *A* e *B*.

In [118]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [119]:
A

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']

In [120]:
B

['Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [123]:
C = A + B
C

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *len(A)*

Tamanho da lista A.

In [124]:
len(Acessorios)

8

# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [129]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [130]:
Acessorios[0]

'Rodas de liga'

In [131]:
Acessorios[-1]

'Sensor de chuva'

In [132]:
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [133]:
Carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [134]:
Carros[0][0]

'Jetta Variant'

In [135]:
Carros[0][-2]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [136]:
Carros[0][-2][2]

'Piloto automático'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [137]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [138]:
Acessorios[2:5]

['Piloto automático', 'Bancos de couro', 'Ar condicionado']

In [139]:
Acessorios[2:]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [141]:
Acessorios[:5]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

In [174]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

## *A.sort()*

Ordena a lista *A*.

In [175]:
Acessorios.sort()
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.append(x)*

Adiciona o elemnto *x* no final da lista *A*.

In [176]:
Acessorios.append('Teto Solar')
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Teto Solar']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [177]:
Acessorios.pop()

'Teto Solar'

In [178]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [179]:
Acessorios.pop(3)

'Rodas de liga'

In [180]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [181]:
Acessorios_2 = Acessorios

In [183]:
Acessorios_2.append('4 x 4')
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4',
 '4 x 4']

In [184]:
Acessorios.pop()

'4 x 4'

In [185]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

In [186]:
Acessorios.pop()

'4 x 4'

In [187]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [188]:
Acessorios_2 = Acessorios.copy() # ou pode ser feito Acessorios_2 = Acessorios(:)
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [189]:
Acessorios_2.append('4 x 4')


In [191]:
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

In [190]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [192]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [193]:
for item in Acessorios:
  print(item)

Ar condicionado
Bancos de couro
Piloto automático
Sensor crepuscular
Sensor de chuva
Sensor de estacionamento
Travas elétricas


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [194]:
range(10)

range(0, 10)

In [196]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [197]:
for i in range(10):
  print(i ** 2)

0
1
4
9
16
25
36
49
64
81


In [199]:
quadrado = []
for i in range(10):
  quadrado.append(i ** 2)
quadrado  

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [200]:
[i ** 2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.2 Loops aninhados

In [201]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [202]:
for lista in dados:
  print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [203]:
for lista in dados:
  for item in lista:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [205]:
Novos_Acessorios = []

for lista in dados:
  for item in lista:
    Novos_Acessorios.append(item)
Novos_Acessorios    

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [206]:
list(set(Novos_Acessorios))

['Câmera de estacionamento',
 'Sensor crepuscular',
 '4 X 4',
 'Vidros elétricos',
 'Painel digital',
 'Central multimídia',
 'Piloto automático',
 'Sensor de chuva',
 'Câmbio automático',
 'Sensor de estacionamento',
 'Rodas de liga',
 'Teto panorâmico',
 'Ar condicionado',
 'Bancos de couro',
 'Freios ABS',
 'Controle de estabilidade',
 'Travas elétricas']

### List comprehensions

In [209]:
list(set([item for lista in dados for item in lista]))

['Câmera de estacionamento',
 'Sensor crepuscular',
 '4 X 4',
 'Vidros elétricos',
 'Painel digital',
 'Central multimídia',
 'Piloto automático',
 'Sensor de chuva',
 'Câmbio automático',
 'Sensor de estacionamento',
 'Rodas de liga',
 'Teto panorâmico',
 'Ar condicionado',
 'Bancos de couro',
 'Freios ABS',
 'Controle de estabilidade',
 'Travas elétricas']

# 4.3 Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [210]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [214]:
zero_km_Y = []

for lista in dados:
  if(lista[2] == True):
    zero_km_Y.append(lista)
zero_km_Y    

[['DS5', 2019, True], ['A5', 2019, True]]

### List comprehensions

In [216]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

In [224]:
zero_km_Y, zero_km_N = [],[]

for lista in dados:
  if (lista[2] == True):
    zero_km_Y.append(lista)
  else:
    zero_km_N.append(lista)  
  

In [225]:
zero_km_Y 

[['DS5', 2019, True], ['A5', 2019, True]]

In [226]:
zero_km_N

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [229]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [227]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [228]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [231]:
A, B, C = [],[],[]

for lista in dados:
  if (lista[1] <= 2000):
    A.append(lista)
  elif (lista[1] > 2000 and lista[1] <= 2010):
    B.append(lista)
  else:
    C.append(lista)  


In [232]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [233]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [234]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [235]:
A, B, C = [],[],[]

for lista in dados:
  if (lista[1] <= 2000):
    A.append(lista)
  elif (2000 < lista[1] <= 2010):
    B.append(lista)
  else:
    C.append(lista) 

# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [240]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [241]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

In [31]:
import numpy as np


In [32]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [29]:
from numpy import  arange

In [244]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [245]:
km = np.array([3000, 30000, 15000, 20000])

In [246]:
km

array([ 3000, 30000, 15000, 20000])

In [247]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [248]:
km.dtype

dtype('int64')

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [249]:
km = np.loadtxt(fname = 'carros-km.txt',dtype= int)

In [250]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

### Arrays com duas dimensões

In [251]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [252]:
Acessorios = np.array(dados)    

In [253]:
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [254]:
km.shape

(258,)

In [255]:
Acessorios.shape

(3, 8)

### Comparando desempenho com listas

In [7]:
np_array = np.arange(1000000)

In [8]:
py_list = list(range(1000000))

In [9]:
%time for _ in range(100): np_array *= 2


CPU times: user 59 ms, sys: 0 ns, total: 59 ms
Wall time: 61.7 ms


In [11]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 9.83 s, sys: 2.27 s, total: 12.1 s
Wall time: 12.1 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [12]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [13]:
# idade = 2021 - anos

TypeError: ignored

In [17]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2021, 2006])

In [18]:
idade = 2021 - anos
idade

array([18, 30, 31,  0, 15])

### Operações entre arrays

In [19]:
km_media = km / idade

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


### Operações com arrays de duas dimensões

In [20]:
dados = np.array([km, anos])

In [21]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2021.,  2006.]])

In [22]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [23]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [24]:
dados[1]

array([2003., 1991., 1990., 2021., 2006.])

In [27]:
km_media = dados[0] / (2021 - dados[1])
km_media

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([2467.22222222,  190.4       , 1197.51612903,           nan,
       1717.13333333])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [33]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
contador[0]

0

In [35]:
item =6
index = item - 1
contador[index]

5

In [36]:
contador[-1]

9

In [37]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [38]:
dados[1]

array([2003., 1991., 1990., 2021., 2006.])

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [39]:
dados[1,2]

1990.0

In [40]:
dados[1][2]

1990.0

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [41]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
contador[1:4]

array([1, 2, 3])

In [43]:
contador[1:8:2]

array([1, 3, 5, 7])

In [44]:
contador[::2]

array([0, 2, 4, 6, 8])

In [45]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [46]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2021.,  2006.]])

In [48]:
dados[:,1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [49]:
dados[:,1:3][0] / (2021 - dados[:,1:3][1])

array([ 190.4       , 1197.51612903])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [50]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [52]:
contador[contador > 5 ]

array([6, 7, 8, 9])

In [53]:
dados 

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2021.,  2006.]])

In [54]:
dados[1] > 2000 

array([ True, False, False,  True,  True])

In [55]:
dados[:,dados[1] > 2000 ]

array([[44410.,     0., 25757.],
       [ 2003.,  2021.,  2006.]])

# 5.4 Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [56]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [57]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [58]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [59]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [60]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2021.],
       [25757.,  2006.]])

In [61]:
dados.transpose

<function ndarray.transpose>

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [62]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2021.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [63]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [65]:
contador.reshape((5,2), order = 'C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [66]:
contador.reshape((5,2), order = 'F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [67]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [68]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [70]:
np.array(info_carros).reshape((2,5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [71]:
np.array(info_carros).reshape((5,2),order = 'F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [73]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2021.,  2006.]])

In [77]:
dados_new.resize((3,5), refcheck=False)
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2021.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [78]:
dados_new[2] = dados_new[0] / (2021 - dados_new[1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [79]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2021.        ,
         2006.        ],
       [ 2467.22222222,   190.4       ,  1197.51612903,            nan,
         1717.13333333]])

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [80]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [81]:
anos.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [ ]:
dataset = np.column_stack((anos,km,valor))
dataset

In [84]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [85]:
np.mean(dataset)
# veja não é interessante essa abordagem, talez seja melhor passar qual o eixo trabalhado

48489.14648578811

In [91]:
np.mean(dataset, axis=0)
# axis = 0 ---> colunas

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset, axis=1)
# axis = 0 ---> linhas

In [95]:
np.mean(dataset[:,1], axis=0)

44499.41472868217

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [96]:
np.std(dataset[:,2])

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [97]:
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [98]:
dataset[:,1].sum()

11480849.0

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [99]:
np.sum(dataset, axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])